--1.Pull total number of orders that were completed on 18th March 2023.
SELECT COUNT(DISTINCT Order_id) AS total_orders
FROM SALES
WHERE Date = '2023-03-18';

--2.Pull total number of orders that were completed on 18th March 2023 with the first name ‘John’ and last name Doe’.
SELECT COUNT(DISTINCT s.Order_id) AS total_orders
FROM SALES s
JOIN CUSTOMERS c ON s.Customer_id = c.customer_id
WHERE s.Date = '2023-03-18'
AND c.first_name = 'John'
AND c.last_name = 'Doe';

--3.Pull total number of customers that purchased in January 2023 and the average amount spend per customer.
SELECT COUNT(DISTINCT Customer_id) AS total_customers, AVG(Revenue) AS average_spending
FROM SALES
WHERE Date >= '2023-01-01' AND Date <= '2023-01-31';

--4.Pull the departments that generated less than $600 in 2022.
SELECT i.department, SUM(s.Revenue) AS total_revenue
FROM SALES s
JOIN ITEMS i ON s.Item_id = i.Item_id
WHERE s.Date BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY i.department
HAVING SUM(s.Revenue) < 600;

--5.What is the most and least revenue we have generated by an order.
--Most Revenue
SELECT Order_id, MAX(Revenue) AS max_revenue
FROM SALES;
--Least Revenue
SELECT Order_id, MIN(Revenue) AS min_revenue
FROM SALES;

--6.What were the orders that were purchased in our most lucrative order.
SELECT Order_id
FROM SALES
GROUP BY Order_id
ORDER BY SUM(Revenue) DESC
LIMIT 1;

SELECT Item_id, Quantity
FROM SALES
WHERE Order_id = [Most_Lucrative_Order_Id];
